apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
# - guestbook-ui-deployment-wrong.yaml
- guestbook-ui-svc.yaml
- guestbook-ui-ingress.yaml
- guestbook-ui-hook.yaml
