apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
spec:
  project: guestbook-kustomize
  source:
    repoURL: 'https://github.com/mircea-cosbuc/argocd-example-apps'
    path: kustomize-guestbook/app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mircea-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
